Added circleci-setvars and dockerhub-ls
RedisLabsModules/readies pull request #36
Opened 2021-06-06 11:53 UTC by rafie

2021-06-06 12:01 UTC, chayim commented on bin/dockerhub-ls
> +#!/usr/bin/env python3
Take a look at [docker-hub](https://github.com/amalfra/docker-hub). It provides support for a lot of this.

2021-06-06 12:01 UTC, chayim commented on bin/dockerhub-ls
> +import yaml
Unused import. Try running flake8 against this.

2021-06-06 12:04 UTC, chayim commented on bin/circleci-setvars
> +        self.token = token
Since you don't intend this token to be used again, it shouldn't be set. Or, if you'd like it in the class object it should be prefixed with an underscore to denote ~private.

2021-06-06 12:05 UTC, chayim commented on bin/circleci-setvars
> +        self.headers = {"Circle-Token": token}
self.HEADERS

2021-06-06 12:06 UTC, chayim requested changes
Attached is the final version of the script I was using. I prefer it, as nothing has to be driven from files.
[circle-fix.zip](https://github.com/RedisLabsModules/readies/files/6604152/circle-fix.zip)

2021-06-06 12:10 UTC, chayim commented on bin/dockerhub-ls
> +        tags = dockerhub_query(f"repositories/{org}/{img}/tags", token, 'name')
You don't need to log into docker hub, to perform any of these actions.

2021-06-06 13:28 UTC, rafie commented on bin/dockerhub-ls
> +        tags = dockerhub_query(f"repositories/{org}/{img}/tags", token, 'name')
You do need to login to look at private repos.

2021-06-08 07:38 UTC, chayim commented on bin/dockerhub-ls
> +        tags = dockerhub_query(f"repositories/{org}/{img}/tags", token, 'name')
Obviously I only test on public repos. :rofl:

2021-06-08 10:22 UTC, merged